name: Build and Release App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_FILE: sr7key.jks
          KEYSTORE_PASSWORD: "@sr7mods"
          KEY_ALIAS: sr7mods
          KEY_PASSWORD: "@sr7mods"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/app-release.apk
          tag_name: release-${{ github.run_number }}
          name: Release ${{ github.run_number }}
          generate_release_notes: true
          
